# Name of your application. Used to uniquely configure containers.
service: store

# Name of the container image.
image: wralak/store

# Deploy to these servers.
servers:
  web:
    - 192.168.0.1

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: wralak



  proxy:
  # Kamal will use Traefik as a reverse proxy and issue SSL via Let's Encrypt
  app:
    image: ghcr.io/basecamp/kamal-traefik
    args:
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.le.acme.email=your-email@example.com
      - --certificatesresolvers.le.acme.storage=/etc/traefik/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.httpchallenge=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik-certificates:/etc/traefik

